spring.application.name=vitaltacc

# Conexión con tu base de datos de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vitaltacc
spring.datasource.username=root
spring.datasource.password=juanga438197

# Configuración extra para que Spring nos ayude
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
